spring.application.name=oauth
spring.security.oauth2.client.registration.google.client-id=439656640429-nc34jg0cul5raundq83huvdta179l6bd.apps.googleusercontent.com

spring.security.oauth2.client.registration.google.client-secret=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

spring.security.oauth2.client.registration.google.scope=email,profile
